server:
  port: 9091
  servlet:
        context-path: /example

spring:
  application:
    name: service-hi

eureka:
  client:
    serviceUrl:
       defalutZone: localhost:8761/eureka/
            
 
